### ISSUE TITLE
Could you please provide the make_spi_mcs.tcl and program_spi.tcl ?

### ISSUE THREAD

**Issue by matlinsas** [microideax/Open-Dnn#1]
I can't find above files. 
Could you please help to check them in?

**Comment by microideax** [comment]
Where do you need to use these files?
If the tcl for the system construction is not working well, please refer to the block design in the pdf files to construct your own systems.

Also, could you please let me know how do you encounter with these missing files?

Sent from my iPhone

On 27 May 2019, at 20:26, matlinsas <notifications@github.com<mailto:notifications@github.com>> wrote:


I can't find above files.
Could you please help to check them in?

**Comment by matlinsas** [comment]
Thanks for your replay~ It's OK now. I tried the build_system_local.tcl.. it works...
